spring:
  profiles:
    active: dev
    include: secret
  application:
    name: avtoreal-monitor
  threads:
    virtual:
      enabled: true
server:
  port: 0

app:
  api-endpoint: https://api.telegram.org
  # Provide your secrets here or in the application-secret.yml file
  #  bot-token: 1234567890:AABBCCDDaabbccdd
  #  telegram-chat-id: 111111111
  #  avtoreal-login: login
  #  avtoreal-password: password
  #  driving-instructor: INSTRUCTOR FULL NAME